if (steps.init.typ == "nav") {
  const cards = [
    {
      id: "AD",
      title: "AD",
      desc: "",
      img:
        "https://www.thesportsdb.com/images/media/league/fanart/17brr81520017442.jpg",
      works: true,
      oth: "",
    },
    {
      id: "uru",
      title: "Uruguay",
      desc: "AUVO Automovilismo | Karting | +",
      img:
        "https://www.thesportsdb.com/images/media/league/fanart/17brr81520017442.jpg",
      works: true,
      oth: "",
      orgs: [
        {
          id: "auvo",
          title: "AUVO",
          desc: "Asociacion Uruguaya de Volantes",
          img: "https://pbs.twimg.com/media/ES2xUXRUUAMsWfV?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "uyst",
              title: "Superturismo",
              desc: "Superturismo",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "uyse",
              title: "Superescarabajos",
              desc: "Superescarabajos",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "uyss",
              title: "Super Sonic",
              desc: "Super Sonic",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "uyf4",
              title: "F4 Uruguaya",
              desc: "F4 Uruguaya",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "uyc2",
              title: "Clase II",
              desc: "Clase II",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "uyth",
              title: "Turismo Historico",
              desc: "Turismo Historico",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "fuk",
          title: "FUK",
          desc: "Fed. Uruguaya de Karting",
          img: "https://pbs.twimg.com/media/CjqyJjJWEAAJ_17?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "fukjrm",
              title: "Junior Max",
              desc: "Junior Max",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "fukcad",
              title: "Cadetes",
              desc: "Cadetes",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "fuks200",
              title: "Shifter 200",
              desc: "Shifter 200",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "fuksr",
              title: "Senior",
              desc: "Senior",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "fuks250",
              title: "Shifter 250",
              desc: "Shifter 250",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "fuksp",
              title: "Shifter PRO",
              desc: "Shifter PRO",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "fukmr",
              title: "Master",
              desc: "Master",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "cur",
          title: "CUR",
          desc: "Club Uruguayo de Rally",
          img:
            "https://static.wixstatic.com/media/047cb5_c37a130d368d469c9a2f59dc35bdd6d4~mv2.jpg/v1/fill/w_925,h_469,al_c,q_90,usm_0.66_1.00_0.01/047cb5_c37a130d368d469c9a2f59dc35bdd6d4~mv2.webp",
          works: true,
          oth: "",
          cats: [
            {
              id: "uyrn",
              title: "Rally Nacional",
              desc: "Rally Nacional",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "",
          title: "AD",
          desc: "",
          img:
            "https://www.thesportsdb.com/images/media/league/badge/lfdwhk1552839818.png",
          works: true,
          oth: "",
        },
        {
          id: "gpu",
          title: "GPU",
          desc: "Gran Premio del Uruguay",
          img:
            "http://www.19capitaleshistorico.com/files/large/697715ace50799de8ffbc047e0433b6b.jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "capi",
              title: "19 Capitales",
              desc: "19 Capitales Historico",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "other",
          title: "OTROS",
          desc: "",
          img: "https://pbs.twimg.com/media/D5G3YFFW0AAVBf2?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "",
              title: " ",
              desc: " ",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "",
          title: "AD",
          desc: "",
          img:
            "https://www.thesportsdb.com/images/media/league/badge/lfdwhk1552839818.png",
          works: true,
          oth: "",
        },
      ],
    },
    {
      id: "arg",
      title: "Argentina",
      desc: "ACTC | TC2000 | TopRace | +",
      img:
        "https://www.thesportsdb.com/images/media/league/fanart/17brr81520017442.jpg",
      works: true,
      oth: "",
      orgs: [
        {
          id: "actc",
          title: "ACTC",
          desc: "Turismo Carretera",
          img: "https://pbs.twimg.com/media/EUh9EkqWAAARsmE?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "tc",
              title: "TC",
              desc: "Turismo Carretera",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "tcp",
              title: "TCP",
              desc: "TC Pista",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "tcm",
              title: "TCM",
              desc: "TC Moura",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "tcpm",
              title: "TCPM",
              desc: "TC Pista Moura",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "tcpk",
              title: "TCPK",
              desc: "TC Pick Up",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "tc",
          title: "TC2000",
          desc: "Turismo Competición 2000",
          img: "https://pbs.twimg.com/media/EWIFVD3XsAcGDSx?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "tc2000",
              title: "TC 2000",
              desc: "TC 2000",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "stc2000",
              title: "Super TC 2000",
              desc: "Super TC 2000",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "f20r",
              title: "F2.0 Renault",
              desc: "Formula 2.0 Renault",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "toprace",
          title: "TOPRACE",
          desc: "",
          img: "https://pbs.twimg.com/media/D9c-hhxXUAMAUGt?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "toprace",
              title: "TopRace",
              desc: "TopRace",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "trseries",
              title: "TR Series",
              desc: "TopRace Series",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,

              oth: "",
            },
            {
              id: "trjunior",
              title: "TR Junior",
              desc: "TopRace Junior",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "",
          title: "AD",
          desc: "",
          img:
            "https://www.thesportsdb.com/images/media/league/badge/lfdwhk1552839818.png",
          works: true,
          oth: "",
        },
        {
          id: "apat",
          title: "APAT",
          desc: "Turismo Nacional",
          img: "https://pbs.twimg.com/media/EWOfzylXYAAxtLZ?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "tnc2",
              title: "TN C2",
              desc: "Turismo Nacional C2",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "tnc3",
              title: "TN C3",
              desc: "Turismo Nacional C3",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "aptp",
          title: "APTP",
          desc: "Turismo Pista",
          img: "https://pbs.twimg.com/media/EUhVHsOXkAIXLSo?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "tpc1",
              title: "TP C1",
              desc: "Turismo Pista C1",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "tpc2",
              title: "TP C2",
              desc: "Turismo Pista C2",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "tpc3",
              title: "TP C3",
              desc: "Turismo Pista C3",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "carx",
          title: "CARX",
          desc: "Rally Cross",
          img:
            "https://pbs.twimg.com/media/EUJNsjEXgAUg4dK?format=jpg&name=4096x4096",
          works: true,
          oth: "",
          cats: [
            {
              id: "rxmr",
              title: "Maxi Rally",
              desc: "Maxi Rally",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "rxn4",
              title: "Clase N4",
              desc: "Clase N4",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "rxjr",
              title: "Junior",
              desc: "Junior",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "other",
          title: "OTROS",
          desc: "",
          img: "https://pbs.twimg.com/media/D5G3YFFW0AAVBf2?format=jpg",
          works: true,
          oth: "",
          cats: [
            {
              id: "f4ng",
              title: "F4 NG",
              desc: "Formula 4 Nueva Generacion",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "",
          title: "AD",
          desc: "",
          img:
            "https://www.thesportsdb.com/images/media/league/badge/lfdwhk1552839818.png",
          works: true,
          oth: "",
        },
      ],
    },
    {
      id: "int",
      title: "International",
      desc: "F1 | IndyCar | Nascar | Formula-E | +",
      img:
        "https://www.thesportsdb.com/images/media/league/fanart/17brr81520017442.jpg",
      works: true,
      oth: "",
      orgs: [
        {
          id: "f1",
          title: "F1",
          desc: "Formula One",
          img:
            "https://www.thesportsdb.com/images/media/league/fanart/17brr81520017442.jpg/preview",
          works: true,
          oth: "",
          cats: [
            {
              id: "f1",
              title: "F1",
              desc: "F1",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "f2",
              title: "F2",
              desc: "F2",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "f3",
              title: "F3",
              desc: "F3",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "indycar",
          title: "INDYCAR",
          desc: "IndyCar Series",
          img:
            "https://www.thesportsdb.com/images/media/league/fanart/sqrpsv1481021448.jpg/preview",
          works: true,
          oth: "",
          cats: [
            {
              id: "indyc",
              title: "IndyCar",
              desc: "IndyCar",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "indyl",
              title: "Indy Lights",
              desc: "IndyLights",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "indyp",
              title: "Indy PRO 2000",
              desc: "Indy PRO 2000",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "nascar",
          title: "NASCAR",
          desc: "NASCAR Cup Series",
          img:
            "https://www.thesportsdb.com/images/media/league/fanart/ruxrxu1421686012.jpg/preview",
          works: true,
          oth: "",
          cats: [
            {
              id: "nascar",
              title: "NASCAR",
              desc: "NASCAR",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "nascarxs",
              title: "NASCAR XS",
              desc: "NASCAR Xfinity Series",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "nascartk",
              title: "NASCAR Truck",
              desc: "NASCAR Truck",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "",
          title: "AD",
          desc: "",
          img:
            "https://www.thesportsdb.com/images/media/league/badge/lfdwhk1552839818.png/preview",
          works: true,
          oth: "",
        },
        {
          id: "fe",
          title: "FORMULA E",
          desc: "FIA Formula E",
          img:
            "https://www.thesportsdb.com/images/media/league/fanart/nemohs1520358277.jpg/preview",
          works: true,
          oth: "",
          cats: [
            {
              id: "fe",
              title: "Formula E",
              desc: "Formula E",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "dakar",
          title: "DAKAR",
          desc: "The Dakar Rally",
          img:
            "https://www.thesportsdb.com/images/media/league/fanart/xtsuxr1454423377.jpg/preview",
          works: true,
          oth: "",
          cats: [
            {
              id: "dakarc",
              title: "Cars",
              desc: "Cars",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "dakart",
              title: "Trucks",
              desc: "Trucks",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "dakarb",
              title: "Bikes",
              desc: "Bikes",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "dakarq",
              title: "Quads",
              desc: "Quads",
              works: false,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "otherc",
          title: " + CARS",
          desc: "WRC, WEC, WRX, WTCR",
          img:
            "https://www.thesportsdb.com/images/media/league/fanart/wqrtsr1421443672.jpg/preview",
          works: true,
          oth: "",
          cats: [
            {
              id: "wrc",
              title: "WRC",
              desc: "World Rally Championship",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "wrx",
              title: "WRX",
              desc: "World Rallycross Championship",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "wec",
              title: "WEC",
              desc: "World Endurance Championship",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "wtcr",
              title: "WTCR",
              desc: "FIA World Touring Car",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "",
          title: "AD",
          desc: "",
          img:
            "https://www.thesportsdb.com/images/media/league/badge/lfdwhk1552839818.png",
          works: true,
          oth: "",
        },
        {
          id: "motogp",
          title: "MOTOGP",
          desc: "MotoGP",
          img:
            "https://www.thesportsdb.com/images/media/league/fanart/srvrsu1432342683.jpg/preview",
          works: true,
          oth: "",
          cats: [
            {
              id: "mgp",
              title: "MotoGP",
              desc: "MotoGP",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "mgp2",
              title: "Moto 2",
              desc: "Moto 2",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "mgp3",
              title: "Moto 3",
              desc: "Moto 3",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "otherm",
          title: " + MOTO",
          desc: "SBK, SX, MX",
          img:
            "https://www.thesportsdb.com/images/media/league/fanart/bsve911575183019.jpg/preview",
          works: true,
          oth: "",
          cats: [
            {
              id: "sbk",
              title: "Superbike",
              desc: "Superbike World Championship",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "mxgp",
              title: "MXGP",
              desc: "Motocross World Championship",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "motoe",
              title: "MotoE",
              desc: "MotoE World Cup",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "amasx",
              title: "AMA Supercross",
              desc: "AMA Supercross Championship",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "amamx",
              title: "AMA Motocross",
              desc: "AMA Motocross Championship",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "mantt",
              title: "Isle of Man TT",
              desc: " Isle of Man TT",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
      ],
    },
    {
      id: "vir",
      title: "Virtual",
      desc: "F1 ESports | IndyCar iRacing | ENascar | +",
      img:
        "https://www.thesportsdb.com/images/media/league/fanart/17brr81520017442.jpg",
      works: true,
      oth: "",
      orgs: [
        {
          id: "vir1",
          title: "VIRTUAL",
          desc: "",
          img:
            "https://pbs.twimg.com/media/EXwlziuWAAIoQUB?format=jpg&name=medium",
          works: true,
          oth: "",
          cats: [
            {
              id: "vf1",
              title: "F1 Esports",
              desc: "F1 Esports Virtual GP",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "virl",
              title: "INDYCAR iRacing",
              desc: "INDYCAR iRacing Challenge",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "vnascar",
              title: "ENASCAR iRacing",
              desc: "ENASCAR iRacing Pro Series",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "vfe",
              title: "F-E Race@Home",
              desc: "Formula E Race@Home Challenge",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
            {
              id: "vtcre",
              title: "TCR Europe SIM",
              desc: "TCR Europe SIM Racing",
              works: true,
              chYearIni: 2000,
              chYearFin: 2020,
              chTypes: [
                { value: "0", name: "Pilot", disabled: false },
                { value: "1", name: "Team", disabled: false },
                { value: "2", name: "Constructor", disabled: false },
              ],
              evYearIni: 2000,
              evYearFin: 2020,
              oth: "",
            },
          ],
        },
        {
          id: "",
          title: "AD",
          desc: "",
          img:
            "https://www.thesportsdb.com/images/media/league/badge/lfdwhk1552839818.png",
          works: true,
          oth: "",
        },
      ],
    },
    {
      id: "AD",
      title: "AD",
      desc: "",
      img:
        "https://www.thesportsdb.com/images/media/league/fanart/17brr81520017442.jpg",
      works: true,
      oth: "",
    },
  ];
  this.result = cards;
}
